--- 
- name: Install java and maven
  hosts: 3.17.9.52
  become: yes
  tasks:
  - name: Update yum repo cache
    ansible.builtin.yum:
      update_cache: yes
  - name: Install java
    ansible.builtin.yum:
      name: java-11-amazon-corretto
      state: present
  
- name: Install Maven 
  hosts: 3.17.9.52
  become: yes
  tasks: 
  - name: Download Maven archive
    ansible.builtin.get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
      dest: /tmp/apache-maven-3.9.6-bin.tar.gz
  - name: Ensure Maven is in PATH for ec2-user
    ansible.builtin.unarchive:
      src: /tmp/apache-maven-3.9.6-bin.tar.gz
      dest: /opt/
      remote_src: yes
  - name: Ensure Maven is in PATH for ec2-user
    ansible.builtin.lineinfile:
      path: /home/ec2-user/.bash_profile
      line: |
        export M2_HOME=/opt/apache-maven-3.9.6
        export PATH=$PATH:$M2_HOME/bin

- name: Build the application
  hosts: 3.17.9.52
  gather_facts: False
  tasks:
  - name: Build Jar 
    ansible.builtin.command:
      chdir: /home/ec2-user/ansible-exercise/java-maven-app
      cmd: mvn clean install