--- 
- name: Install java and maven
  hosts: 3.17.9.52
  become: yes
  tasks:
  - name: Update yum repo cache
    ansible.builtin.yum:
      update_cache: yes
  - name: Install java
    ansible.builtin.yum:
      name: java-11-amazon-corretto
      state: present
  
- name: Install Maven 
  hosts: 3.17.9.52
  become: yes
  tasks: 
  - name: Download Maven archive
    ansible.builtin.get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
      dest: /tmp/apache-maven-3.9.6-bin.tar.gz
  - name: Ensure Maven is in PATH for ec2-user
    ansible.builtin.unarchive:
      src: /tmp/apache-maven-3.9.6-bin.tar.gz
      dest: /opt/
      remote_src: yes
  - name: Ensure Maven is in PATH for ec2-user
    ansible.builtin.lineinfile:
      path: /home/ec2-user/.bashrc
      line: |
        export M2_HOME=/opt/apache-maven-3.9.6
        export PATH=$PATH:$M2_HOME/bin
      create: yes
      state: present
  handlers:
  - name: Source Maven path
    become: True
    become_user: ec2-user
    command: source /home/ec2-user/.bashrc
