- name: Deploy manifests in k8s cluster 
  hosts: localhost
  tasks:
  - name: Login to Docker locally to create .dockerjson config file
    community.docker.docker_login:
      registry_url: https://index.docker.io/v1/
      username: "{{ docker_user }}"
      password: "{{ docker_pass }}"