- name: Deploy manifests in k8s cluster 
  hosts: localhost
  tasks:
  - name: Login to Docker locally to create .dockerjson config file
    community.docker.docker_login:
      registry_url: https://index.docker.io/v1/
      username: "{{ docker_user }}"
      password: "{{ docker_pass }}"

  - name: Create Docker registry secret 
    kubernetes.core.k8s:
      state: present 
      kubeconfig: ~/.kube/config
      definition:
        apiVersion: v1 
        kind: Secret 
        type: kubernetes.io/dockerconfigjson
        metadata:
          name: my-registry-key
          namespace: default  
        data: 
          .dockerconfigjson: "{{ lookup('file', '~/.docker/config.json') | b64encode }}"

  - name: Add Bitnami repository
    kubernetes.core.helm_repository:
      name: bitnami 
      repo_url: https://charts.bitnami.com/bitnami
      kubeconfig: ~/.kube/config
  - name: Check for differences with helm-diff
    command: helm diff upgrade mysql-release bitnami/mysql --namespace default --kubeconfig ~/.kube/config -f /home/ec2-user/ansible-exercise/kubernetes-manifests/mysql-chart-values-minikube.yaml
    register: helm_diff_result
    ignore_errors: true

  - name: Deploy Mysql chart with 3 replicas 
    kubernetes.core.helm: 
      name: mysql-release
      chart_ref: bitnami/mysql
      release_namespace: default
      values: "{{ lookup('file', 'kubernetes-manifests/mysql-chart-values-minikube.yaml') | from_yaml }}"
    when: helm_diff_result.rc != 0
  - name: Deploy java application manifests

    kubernetes.core.k8s:
      definition: "{{ lookup('file', '{{ item }}') }}"
      state: present
      kubeconfig: ~/.kube/config
      namespace: default
    with_fileglob:
      - kubernetes-manifests/java-*.yaml

      