--- 
- name: Get server IP 
  hosts: localhost 
  gather_facts: false
  vars_files:
  - jenkins-vars
  tasks:
  - name: Get public IP address of the ec2 instance
    amazon.aws.ec2_instance_info:
      region: "{{ region }}"
      filters:
        "tag:Name": "jenkins-server"
    register: ec2_result
  
# Preparing Jenkins Server by installing Docker
- name: Preapre server for Jenkins
  hosts: "{{ hostvars['localhost']['ec2_result'].instances[0].public_ip_address }}"
  become: yes 
  tasks: 
  - name: Install Docker
    ansible.builtin.yum:
      name: docker 
      update_cache: yes
      state: latest
  - name: Start Docker
    ansible.builtin.systemd:
      name: docker
      state: started
      enabled: yes

- name: Add user to docker group 
  hosts: "{{ hostvars['localhost']['ec2_result'].instances[0].public_ip_address }}"
  become: yes
  tasks:
  - name: Add ec2-user to docker group 
    ansible.builtin.user:
      name: ec2-user
      groups: docker
      append: yes
  - name: Reconnect to server session
    ansible.builtin.meta: reset_connection

- name: Start Jenkins container on ec2 Instance 
  hosts: "{{ hostvars['localhost']['ec2_result'].instances[0].public_ip_address }}"
  become: yes
  tasks:
  - name: Get location of docker executable
    ansible.builtin.command:
      cmd: which docker 
    register: docker_result
  
  - name: Start Jenkins container 
    community.docker.docker_container:
      name: jenkins
      image: jenkins/jenkins:lts
      volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ docker_result.stdout }}:/usr/bin/docker"
      ports:
      - 8080:8080
      - 50000:50000 
    
  - name: Set Docker permission inside Jenkins container
    community.docker.docker_container_exec:
      container: jenkins
      command: chmod 666 /var/run/docker.sock
    
  - name: Get Jenkins admin password from the container
    community.docker.docker_container_exec:
      container: jenkins
      command: cat /var/jenkins_home/secrets/initialAdminPassword
    register: jenkins_pwd 
    retries: 5
    delay: 10
    until: jenkins_pwd.exit_code == 0
  
  - name: Print Jenkins admin password
    ansible.builtin.debug:
      msg: "Jenkins admin password: {{ jenkins_pwd.stdout }}"