--- 
- name: Provision Jenkins server
  hosts: localhost
  gather_facts: false
  vars_files:
  - jenkins-vars
  tasks:
  - name: Get vpc_information
    amazon.aws.ec2_vpc_net_info:
      region: "{{ region }}"
    register: vpc_result
  - ansible.builtin.debug: msg="{{ vpc_result }}"