--- 
- name: Provision Jenkins server
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Get vpc_information
    amazon.aws.ec2_vpc_net_info:
      region: us-east-2
    register: vpc_result
  - ansible.builtin.debug: msg="{{ vpc_result }}"