apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  labels:
    app: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: java-app
        image: chinmayapradhan/java-mysql-app:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: db_user
              name: db-secret
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              key: db_pwd
              name: db-secret
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: db_name
              name: db-secret
        - name: DB_SERVER 
          valueFrom:
            configMapKeyRef:
              key: db_server
              name: db-config
--- 
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer